### ISSUE TITLE
Panic when using DirectX 12 as backend

### ISSUE THREAD

**Issue by Caelum100** [Caelum100/Luminite#1]
`thread 'main' panicked at 'called Result::unwrap() on an Err value: Other', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:463
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:350
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:328
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<gfx_hal::pso::CreationError>
             at C:\projects\rust\src\libcore\macros.rs:26
  10: core::result::Result<gfx_backend_dx12::native::GraphicsPipeline, gfx_hal::pso::CreationError>::unwrap<gfx_backend_dx12::native::GraphicsPipeline,gfx_hal::pso::CreationError>
             at C:\projects\rust\src\libcore\result.rs:782
  11: luminite::render::factory::RenderBuilder<gfx_backend_dx12::Backend>::finish
             at .\src\render\factory.rs:285
  12: luminite::render::factory::RenderBuilder<gfx_backend_dx12::Backend>::build
             at .\src\render\factory.rs:122
  13: luminite::render::create_context
             at .\src\render\mod.rs:56
  14: luminite::main
             at .\src\main.rs:27
  15: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  16: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  17: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:310
  18: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  19: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  20: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:374
  21: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  22: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  23: main
  24: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  25: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  26: BaseThreadInitThunk
  27: RtlUserThreadStart`

**Comment by Caelum100** [comment]
Fixed in bfc861a.
